"""v2 data platform

Revision ID: f961eb6a358a
Revises: 9bae1133cb73
Create Date: 2026-09-27 05:10:24.844176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f961eb6a358a'
down_revision: Union[str, Sequence[str], None] = '9bae1133cb73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('publisher', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('MARKET_PRICES', 'WEATHER', 'INVENTORY', name='datakind', native_enum=False, length=32), nullable=False),
    sa.Column('origin', sa.Enum('OFFICIAL_API', 'PUBLIC_API', 'USER_UPLOAD', name='sourceorigin', native_enum=False, length=32), nullable=False),
    sa.Column('homepage_url', sa.String(length=500), nullable=False),
    sa.Column('license', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('update_frequency', sa.String(length=160), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources')),
    sa.UniqueConstraint('key', name=op.f('uq_data_sources_key'))
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('triggered_by_id', sa.Uuid(), nullable=True),
    sa.Column('trigger', sa.Enum('MANUAL', 'SCHEDULED', 'UPLOAD', name='runtrigger', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', name='runstatus', native_enum=False, length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_received', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('rows_unchanged', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ingestion_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_ingestion_runs_source_id_data_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], name=op.f('fk_ingestion_runs_triggered_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_index(op.f('ix_ingestion_runs_organization_id'), 'ingestion_runs', ['organization_id'], unique=False)
    op.create_index('ix_ingestion_runs_source_started', 'ingestion_runs', ['source_id', 'started_at'], unique=False)
    op.create_table('ingestion_issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.Enum('ERROR', 'WARNING', name='issueseverity', native_enum=False, length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], name=op.f('fk_ingestion_issues_run_id_ingestion_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_issues'))
    )
    op.create_index(op.f('ix_ingestion_issues_run_id'), 'ingestion_issues', ['run_id'], unique=False)
    op.create_table('market_prices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('market', sa.String(length=160), nullable=False),
    sa.Column('commodity', sa.String(length=120), nullable=False),
    sa.Column('variety', sa.String(length=120), nullable=False),
    sa.Column('grade', sa.String(length=60), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('modal_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_market_prices_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], name=op.f('fk_market_prices_run_id_ingestion_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_market_prices_source_id_data_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_prices')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_market_prices_dedupe_key'))
    )
    op.create_index(op.f('ix_market_prices_arrival_date'), 'market_prices', ['arrival_date'], unique=False)
    op.create_index('ix_market_prices_commodity_date', 'market_prices', ['commodity', 'arrival_date'], unique=False)
    op.create_index('ix_market_prices_org_source', 'market_prices', ['organization_id', 'source_id'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('CURRENT', 'DAILY', name='weatherkind', native_enum=False, length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('wind_kmh', sa.Float(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('temp_max_c', sa.Float(), nullable=True),
    sa.Column('temp_min_c', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_weather_observations_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], name=op.f('fk_weather_observations_run_id_ingestion_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_weather_observations_source_id_data_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_weather_observations_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_observations')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_weather_observations_dedupe_key'))
    )
    op.create_index('ix_weather_obs_wh_kind_time', 'weather_observations', ['warehouse_id', 'kind', 'observed_at'], unique=False)
    op.create_index(op.f('ix_weather_observations_organization_id'), 'weather_observations', ['organization_id'], unique=False)
    op.add_column('commodities', sa.Column('market_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commodities', 'market_name')
    op.drop_index(op.f('ix_weather_observations_organization_id'), table_name='weather_observations')
    op.drop_index('ix_weather_obs_wh_kind_time', table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index('ix_market_prices_org_source', table_name='market_prices')
    op.drop_index('ix_market_prices_commodity_date', table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_arrival_date'), table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_ingestion_issues_run_id'), table_name='ingestion_issues')
    op.drop_table('ingestion_issues')
    op.drop_index('ix_ingestion_runs_source_started', table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_organization_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
