"""v3 provenance and source health

Revision ID: 948c250a6d15
Revises: f961eb6a358a
Create Date: 2026-09-27 06:00:12.546290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948c250a6d15'
down_revision: Union[str, Sequence[str], None] = 'f961eb6a358a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_state',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_scheduler_state'))
    )
    op.create_table('organization_source_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('auto_refresh', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_source_settings_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_organization_source_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_source_settings')),
    sa.UniqueConstraint('organization_id', 'source_key', name='uq_org_source_settings')
    )
    op.create_index(op.f('ix_organization_source_settings_organization_id'), 'organization_source_settings', ['organization_id'], unique=False)
    op.add_column('ingestion_runs', sa.Column('rows_duplicate', sa.Integer(), server_default='0', nullable=False))
    op.add_column('ingestion_runs', sa.Column('error_kind', sa.String(length=32), nullable=True))
    op.add_column('ingestion_runs', sa.Column('endpoint', sa.String(length=500), nullable=True))
    op.add_column('inventory_items', sa.Column('data_origin', sa.Enum('SYNTHETIC_DEMO', 'MANUAL_ENTRY', 'CSV_IMPORT', 'API', name='dataorigin', native_enum=False, length=32), server_default='MANUAL_ENTRY', nullable=False))
    op.add_column('inventory_movements', sa.Column('data_origin', sa.Enum('SYNTHETIC_DEMO', 'MANUAL_ENTRY', 'CSV_IMPORT', 'API', name='dataorigin', native_enum=False, length=32), server_default='MANUAL_ENTRY', nullable=False))
    op.add_column('market_prices', sa.Column('unit', sa.String(length=20), server_default='INR/quintal', nullable=False))
    op.add_column('market_prices', sa.Column('source_record_id', sa.String(length=160), nullable=True))
    op.add_column('market_prices', sa.Column('source_dataset', sa.String(length=255), nullable=True))
    op.add_column('market_prices', sa.Column('source_endpoint', sa.String(length=500), nullable=True))
    op.add_column('market_prices', sa.Column('raw_reference', sa.JSON(), nullable=True))
    op.add_column('market_prices', sa.Column('validation_status', sa.Enum('ACCEPTED', 'ACCEPTED_WITH_WARNING', name='validationstatus', native_enum=False, length=32), server_default='ACCEPTED', nullable=False))
    op.add_column('market_prices', sa.Column('validation_notes', sa.JSON(), nullable=True))
    op.add_column('warehouses', sa.Column('data_origin', sa.Enum('SYNTHETIC_DEMO', 'MANUAL_ENTRY', 'CSV_IMPORT', 'API', name='dataorigin', native_enum=False, length=32), server_default='MANUAL_ENTRY', nullable=False))
    op.add_column('weather_observations', sa.Column('rain_mm', sa.Float(), nullable=True))
    op.add_column('weather_observations', sa.Column('wind_gust_kmh', sa.Float(), nullable=True))
    op.add_column('weather_observations', sa.Column('wind_max_kmh', sa.Float(), nullable=True))
    op.add_column('weather_observations', sa.Column('precipitation_probability', sa.Float(), nullable=True))
    op.add_column('weather_observations', sa.Column('source_endpoint', sa.String(length=500), nullable=True))
    op.add_column('weather_observations', sa.Column('raw_reference', sa.JSON(), nullable=True))
    op.add_column('weather_observations', sa.Column('validation_status', sa.Enum('ACCEPTED', 'ACCEPTED_WITH_WARNING', name='validationstatus', native_enum=False, length=32), server_default='ACCEPTED', nullable=False))
    op.add_column('weather_observations', sa.Column('validation_notes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

    # Backfill: records in seeded demo workspaces were invented by the seed script.
    for table in ("warehouses", "inventory_items", "inventory_movements"):
        op.execute(
            f"UPDATE {table} SET data_origin = 'SYNTHETIC_DEMO' "
            "WHERE organization_id IN (SELECT id FROM organizations WHERE is_demo = true)"
        )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_observations', 'validation_notes')
    op.drop_column('weather_observations', 'validation_status')
    op.drop_column('weather_observations', 'raw_reference')
    op.drop_column('weather_observations', 'source_endpoint')
    op.drop_column('weather_observations', 'precipitation_probability')
    op.drop_column('weather_observations', 'wind_max_kmh')
    op.drop_column('weather_observations', 'wind_gust_kmh')
    op.drop_column('weather_observations', 'rain_mm')
    op.drop_column('warehouses', 'data_origin')
    op.drop_column('market_prices', 'validation_notes')
    op.drop_column('market_prices', 'validation_status')
    op.drop_column('market_prices', 'raw_reference')
    op.drop_column('market_prices', 'source_endpoint')
    op.drop_column('market_prices', 'source_dataset')
    op.drop_column('market_prices', 'source_record_id')
    op.drop_column('market_prices', 'unit')
    op.drop_column('inventory_movements', 'data_origin')
    op.drop_column('inventory_items', 'data_origin')
    op.drop_column('ingestion_runs', 'endpoint')
    op.drop_column('ingestion_runs', 'error_kind')
    op.drop_column('ingestion_runs', 'rows_duplicate')
    op.drop_index(op.f('ix_organization_source_settings_organization_id'), table_name='organization_source_settings')
    op.drop_table('organization_source_settings')
    op.drop_table('scheduler_state')
    # ### end Alembic commands ###
